<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ak_pagetreetools"
 *
 * Auto generated by Extension Builder 2014-03-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Pagetree Tools',
	'description' => 'Enhances the context menu of the pagetree',
	'category' => 'plugin',
	'author' => 'Andreas Kießling',
	'author_email' => 'andreas.kiessling@web.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>